# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e17b55c888c7d5de42c1742d29041b6ea91694a401b64825516bfcc44944053a8ecdf6664c026b05da114821baea9cbe527810f988a2cadddbf0b95cbfb4eb8

test:
  secret_key_base: 2264ed053f7ce2685b805a0b65d39beeec7a5d0667c4e5e51213ad8c56c00620f300ed600477208e473a1a9429aa69b2cfb2d34cde5ed44a615eb2894ee9fb71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
